version: '3'

services:
  vorlesungsplan-plus-vue:
    build: .
    image: larsrickert/vorlesungsplan-plus-vue
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: dhbw-beta.rickstack.de
      LETSENCRYPT_HOST: dhbw-beta.rickstack.de

networks:
  default:
    name: nginx-proxy
    external: true
