version: '3'

services:
  vorlesungsplan-plus:
    build: .
    image: larsrickert/vorlesungsplan-plus
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: dhbw.rickstack.de
      LETSENCRYPT_HOST: dhbw.rickstack.de

networks:
  default:
    external:
      name: nginx-proxy
