version: '3'

services:
  vorlesungsplan-plus:
    build:
      context: ./frontend
      args:
        VITE_APP_API_HOST: 'https://${BACKEND_DOMAIN}'
    image: larsrickert/vorlesungsplan-plus
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: '${FRONTEND_DOMAIN}'
      LETSENCRYPT_HOST: '${FRONTEND_DOMAIN}'

  vorlesungsplan-plus-api:
    build: ./backend
    image: larsrickert/vorlesungsplan-plus-api
    restart: always
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: '${BACKEND_DOMAIN}'
      LETSENCRYPT_HOST: '${BACKEND_DOMAIN}'
    volumes:
      - ./logs:/usr/src/app/dist/logs

networks:
  default:
    name: nginx-proxy
    external: true
