name: Semantic release
on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
  workflow_dispatch:

jobs:
  release_frontend:
    name: Release frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install node modules
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  release_backend:
    name: Release backend
    needs: release_frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # needed because backend release would fail if frontend release pushed new changes (e.g. CHANGELOG.md)
      - name: Pull latest changes from frontend semantic-release
        run: git pull
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install node modules
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  deploy:
    name: Deploy
    needs:
      - release_frontend
      - release_backend
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: GITHUB_SERVER_URL,GITHUB_REPOSITORY
          script: npx nginx-proxy-cli deploy $GITHUB_SERVER_URL/$GITHUB_REPOSITORY --dir=~/nginx-proxy/applications --folder=vorlesungsplan.lars-rickert.de
